{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "operator API"
  },
  "servers": [
    {
      "url": "https://dev-demo-operator.kerma.games"
    }
  ],
  "tags": [],
  "paths": {
    "/api/v1/authenticate": {
      "post": {
        "summary": "New Endpoint",
        "description": "This is your first endpoint! Edit this page to start documenting your API.",
        "operationId": "get_new-endpoint",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "examples": {
                  "OK": {
                    "summary": "OK",
                    "value": {
                      "id": "id_cmiyr3ti8000201kh6i8oadwq",
                      "token": "cmiyr3ti8000201kh6i8oadwq",
                      "currency": "BRL",
                      "balance": "100",
                      "language": "en",
                      "nickName": "rajat"
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string",
                      "example": "id_cmiyr3ti8000201kh6i8oadwq",
                      "description": "Player ID"
                    },
                    "token": {
                      "type": "string",
                      "example": "cmiyr3ti8000201kh6i8oadwq",
                      "description": "Player session token"
                    },
                    "currency": {
                      "type": "string",
                      "example": "BRL",
                      "description": "Game currency"
                    },
                    "balance": {
                      "type": "string",
                      "example": "100",
                      "description": "Player balance"
                    },
                    "language": {
                      "type": "string",
                      "example": "en",
                      "description": "Language code"
                    },
                    "nickName": {
                      "type": "string",
                      "example": "rajat",
                      "description": "Player nickname"
                    }
                  },
                  "required": [
                    "nickName",
                    "language",
                    "balance",
                    "currency",
                    "token",
                    "id"
                  ]
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "token": {
                    "type": "string",
                    "description": "Unique account identifier"
                  }
                },
                "required": [
                  "token"
                ]
              },
              "examples": {
                "New Example": {
                  "summary": "New Example",
                  "value": {
                    "token": "cmiyr3ti8000201kh6i8oadwq"
                  }
                }
              }
            }
          }
        },
        "x-readme": {
          "code-samples": [
            {
              "code": "curl --location 'https://dev-demo-operator.kerma.games/api/v1/authenticate' \\\n--header 'Content-Type: application/json' \\\n--data '{\n    \"token\": \"cmiyr3ti8000201kh6i8oadwq\"\n}'",
              "language": "shell",
              "name": ""
            }
          ],
          "samples-languages": [
            "shell"
          ]
        }
      }
    },
    "/api/v1/transactions": {
      "post": {
        "summary": "Copy of New Endpoint",
        "description": "This is your first endpoint! Edit this page to start documenting your API.",
        "operationId": "post_apiv1authenticate-1",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "examples": {
                  "OK": {
                    "summary": "OK",
                    "value": {
                      "id": "id_cmiyr3ti8000201kh6i8oadwq",
                      "balance": "102",
                      "currency": "BRL"
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string",
                      "example": "id_cmiyr3ti8000201kh6i8oadwq"
                    },
                    "balance": {
                      "type": "string",
                      "example": "102"
                    },
                    "currency": {
                      "type": "string",
                      "example": "BRL"
                    }
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "player": {
                    "type": "string",
                    "description": "Unique account identifier"
                  },
                  "token": {
                    "type": "string"
                  },
                  "gameId": {
                    "type": "string"
                  },
                  "gameCode": {
                    "type": "string"
                  },
                  "betId": {
                    "type": "string"
                  },
                  "betAmount": {
                    "type": "string"
                  },
                  "winAmount": {
                    "type": "string"
                  },
                  "isEndRound": {
                    "type": "string"
                  },
                  "betType": {
                    "type": "string"
                  },
                  "currency": {
                    "type": "string"
                  },
                  "transactionId": {
                    "type": "string"
                  },
                  "created": {
                    "type": "string"
                  },
                  "updated": {
                    "type": "string"
                  },
                  "walletType": {
                    "type": "string"
                  }
                },
                "required": [
                  "player"
                ]
              },
              "examples": {
                "New Example": {
                  "summary": "New Example",
                  "value": {
                    "player": "cmiyr3ti8000201kh6i8oadwq",
                    "token": "",
                    "gameId": "xxx",
                    "gameCode": "pay-day",
                    "betId": "xxx",
                    "betAmount": 1,
                    "winAmount": 2,
                    "isEndRound": true,
                    "betType": "NORMAL",
                    "currency": "USD",
                    "transactionId": "xxx",
                    "created": "x",
                    "updated": "x",
                    "walletType": "CASH"
                  }
                }
              }
            }
          }
        },
        "x-readme": {
          "code-samples": [
            {
              "code": "curl --location 'https://dev-demo-operator.kerma.games/api/v1/transactions' \\\n--header 'Content-Type: application/json' \\\n--data '{\n    \"player\": \"cmiyr3ti8000201kh6i8oadwq\",\n    \"token\": \"\",\n    \"gameId\": \"xxx\",\n    \"gameCode\": \"pay-day\",\n    \"betId\": \"xxx\",\n    \"betAmount\": 1,\n    \"winAmount\": 2,\n    \"isEndRound\": true,\n    \"betType\": \"NORMAL\",\n    \"currency\": \"USD\",\n    \"transactionId\": \"xxx\",\n    \"created\": \"x\",\n    \"updated\": \"x\",\n    \"walletType\": \"CASH\"\n}'",
              "language": "shell",
              "name": ""
            }
          ],
          "samples-languages": [
            "shell"
          ]
        }
      }
    }
  },
  "components": {
    "securitySchemes": {}
  },
  "x-readme": {
    "explorer-enabled": true,
    "proxy-enabled": true
  }
}